POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Carlos",
  "lastname": "Niieddu",
  "email": "carlos.niieddu@example.com",
  "birthdate": "10-09-1998",
  "password": "StrongP@ssw0rd!", 
  "isActive": true,
  "role": "user"  
}

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/role/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdhYnJpZWwuZGVzc2VuYUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczOTkwNzM3MiwiZXhwIjoxNzM5OTEwOTcyfQ.DOD0pk_zbGzin2MAmsfKr6479j-IVU3h90mM7Ey15lA

###

PATCH http://localhost:3000/users/a6ef4d70-4e1d-4e77-80b8-f32327c54d91
Content-Type: application/json

{
  "isActive":false,
  "role":"user"
}
###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email":"gabriel.dessena@example.com",
  "password":"StrongP@ssw0rd!"
}